[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "FastEHR"
version = "0.0.1"

[tool.setuptools]
packages = ["FastEHR.database", "FastEHR.dataloader"]
